### PR TITLE
First commit of the ui ux

### PR DESCRIPTION
**Pull request by swluthuli**
This change is [Reviewable](https://reviewable.io/reviews/chynamyerz/ke-taxi-frontend/5)

### CODE REVIEW

**Review by chynamyerz — CHANGES_REQUESTED** [review]
> Reviewed 26 of 28 files at r1, 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/chynamyerz/ke-taxi-frontend/5)* status: all files reviewed, 2 unresolved discussions (waiting on @swluthuli)

___
*[src/App.tsx, line 35 at r2](https://reviewable.io/reviews/chynamyerz/ke-taxi-frontend/5#-Lu1IO6H4y0xJMSFKooL:-Lu1IO6H4y0xJMSFKooM:bdzum4m) ([raw file](https://github.com/chynamyerz/ke-taxi-frontend/blob/076f2c96b464f14daec0c254efa1b2341d2f5469/src/App.tsx#L35)):*
> ```XML
>       </IonHeader>
> 
>       <IonPage style={{ marginTop: "30px" }}>
> ```

Using "px" is not safe because it is device-dependent. 
Should use a unit that will adjust with any device (check em or %)
___
*[src/screens/Register.tsx, line 3 at r2](https://reviewable.io/reviews/chynamyerz/ke-taxi-frontend/5#-Lu1K_KDCv0lh0Jrl4qx:-Lu1K_KDCv0lh0Jrl4qy:bf4k6j6) ([raw file](https://github.com/chynamyerz/ke-taxi-frontend/blob/076f2c96b464f14daec0c254efa1b2341d2f5469/src/screens/Register.tsx#L3)):*
> ```XML
> import { IonButton, IonInput, IonItem, IonList } from "@ionic/react";
> import React from "react";
> import email from "../assets/images/email.svg";
> ```

Instead of using svg files, is it possible to use ionic icons?
Same for other places where using svg as icons.

**Comment by swluthuli** [comment]
___
*[src/screens/Register.tsx, line 3 at r2](https://reviewable.io/reviews/chynamyerz/ke-taxi-frontend/5#-Lu1K_KDCv0lh0Jrl4qx:-Lu1U6DTEdblYrJxvRww:b-3azhq5) ([raw file](https://github.com/chynamyerz/ke-taxi-frontend/blob/076f2c96b464f14daec0c254efa1b2341d2f5469/src/screens/Register.tsx#L3)):*
<details><summary><i>Previously, chynamyerz wrote…</i></summary><blockquote>

Instead of using svg files, is it possible to use ionic icons?
Same for other places where using svg as icons.
</blockquote></details>

yeah i will try get the corresponding ionicon

**Comment by swluthuli** [comment]
___
*[src/App.tsx, line 35 at r2](https://reviewable.io/reviews/chynamyerz/ke-taxi-frontend/5#-Lu1IO6H4y0xJMSFKooL:-Lu1UOaKEwEx7jCb7uvK:b-7m2y43) ([raw file](https://github.com/chynamyerz/ke-taxi-frontend/blob/076f2c96b464f14daec0c254efa1b2341d2f5469/src/App.tsx#L35)):*
<details><summary><i>Previously, chynamyerz wrote…</i></summary><blockquote>

Using "px" is not safe because it is device-dependent. 
Should use a unit that will adjust with any device (check em or %)
</blockquote></details>

noted

**Review by chynamyerz — APPROVED** [review]
> Reviewed 16 of 17 files at r3.
> *[Reviewable](https://reviewable.io/reviews/chynamyerz/ke-taxi-frontend/5)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by chynamyerz — APPROVED** [review]
> Reviewed 65 of 92 files at r4.
> *[Reviewable](https://reviewable.io/reviews/chynamyerz/ke-taxi-frontend/5)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
